import type { Theme } from "@/types/editor";
import OneDark from "@/themes/oneDark.json";

export const themes: Record<string, Theme> = {
	oneDark: {
		name: "One Dark",
		value: "oneDark",
		ui: {
			background: "#282c34",
			foreground: "#abb2bf",
			border: "#3e4451",
			accent: "#528bff",
			selection: "#3e4451",
			header: "#21252b",
			hover: "#323842",
			muted: "#5c6370",
			success: "#98c379",
			warning: "#d19a66",
			error: "#e06c75",
			info: "#61afef",
		},
		monaco: {
			base: "vs-dark",
			inherit: true,
			...OneDark,
		},
	},
	vsDark: {
		name: "VS Dark",
		value: "vs-dark",
		ui: {
			background: "#1e1e1e",
			foreground: "#d4d4d4",
			border: "#404040",
			accent: "#007acc",
			selection: "#264f78",
			header: "#252526",
			hover: "#2a2d2e",
			muted: "#858585",
			success: "#89d185",
			warning: "#cca700",
			error: "#f48771",
			info: "#75beff",
		},
		monaco: {
			base: "vs-dark",
			inherit: true,
			rules: [],
			colors: {
				"editor.lineHighlightBackground": "#2A2D2E",
				"editor.lineHighlightBorder": "#2A2D2E",
			},
		},
	},
	light: {
		name: "Light",
		value: "vs-light",
		ui: {
			background: "#ffffff",
			foreground: "#000000",
			border: "#e0e0e0",
			accent: "#0066bf",
			selection: "#add6ff",
			header: "#f3f3f3",
			hover: "#f0f0f0",
			muted: "#6e6e6e",
			success: "#388a34",
			warning: "#bf8803",
			error: "#e51400",
			info: "#1a85ff",
		},
		monaco: {
			base: "vs",
			inherit: true,
			rules: [],
			colors: {
				"editor.lineHighlightBackground": "#F0F0F0",
				"editor.lineHighlightBorder": "#F0F0F0",
			},
		},
	},
	solarizedDark: {
		name: "Solarized Dark",
		value: "solarizedDark",
		ui: {
			background: "#002b36",
			foreground: "#839496",
			border: "#073642",
			accent: "#268bd2",
			selection: "#073642",
			header: "#002b36",
			hover: "#586e75",
			muted: "#657b83",
			success: "#859900",
			warning: "#b58900",
			error: "#dc322f",
			info: "#268bd2",
		},
		monaco: {
			base: "vs-dark",
			inherit: true,
			rules: [
				{ token: "comment", foreground: "586e75", fontStyle: "italic" },
				{ token: "keyword", foreground: "859900" },
				{ token: "string", foreground: "2aa198" },
				{ token: "number", foreground: "d33682" },
				{ token: "operator", foreground: "6c71c4" },
				{ token: "function", foreground: "b58900" },
				{ token: "variable", foreground: "cb4b16" },
				{ token: "type", foreground: "93a1a1" },
			],
			colors: {
				"editor.background": "#002b36",
				"editor.foreground": "#839496",
				"editorLineNumber.foreground": "#586e75",
				"editorCursor.foreground": "#268bd2",
				"editor.selectionBackground": "#073642",
				"editor.wordHighlightBackground": "#073642",
				"editorIndentGuide.background": "#586e75",
				"editorBracketMatch.background": "#073642",
				"editorBracketMatch.border": "#268bd2",
				"editor.lineHighlightBackground": "#073642",
				"editor.lineHighlightBorder": "#073642",
			},
		},
	},
	dracula: {
		name: "Dracula",
		value: "dracula",
		ui: {
			background: "#282a36",
			foreground: "#F8F8F2",
			border: "#44475a",
			accent: "#BD93F9",
			selection: "#44475a",
			header: "#282a36",
			hover: "#21222C",
			muted: "#6272A4",
			success: "#50fa7b",
			warning: "#f1fa8c",
			error: "#FF5555",
			info: "#8be9fd",
		},
		monaco: {
			base: "vs-dark",
			inherit: true,
			rules: [
				{ token: "comment", foreground: "#6272A4", fontStyle: "italic" },
				{ token: "keyword", foreground: "#ff79c6" },
				{ token: "string", foreground: "#f1fa8c" },
				{ token: "number", foreground: "#bd93f9" },
				{ token: "operator", foreground: "#ffb86c", background: "ffb86c" },
				{ token: "function", foreground: "#8be9fd", background: "8be9fd" },
				{ token: "variable", foreground: "#50fa7b" },
				{ token: "type", foreground: "#50fa7b" },
			],
			colors: {
				"editor.background": "#282a36",
				"editor.foreground": "#f8f8f2",
				"editorLineNumber.foreground": "#6272a4",
				"editorCursor.foreground": "#ff79c6",
				"editor.selectionBackground": "#44475a",
				"editor.wordHighlightBackground": "#44475a",
				"editorIndentGuide.background": "#44475a",
				"editorBracketMatch.background": "#44475a",
				"editorBracketMatch.border": "#50fa7b",
				"editor.lineHighlightBackground": "#44475a",
				"editor.lineHighlightBorder": "#44475a",
			},
		},
	},
	nord: {
		name: "Nord",
		value: "nord",
		ui: {
			background: "#2e3440",
			foreground: "#d8dee9",
			border: "#4c566a",
			accent: "#88c0d0",
			selection: "#4c566a",
			header: "#2e3440",
			hover: "#434c5e",
			muted: "#616e88",
			success: "#a3be8c",
			warning: "#ebcb8b",
			error: "#bf616a",
			info: "#81a1c1",
		},
		monaco: {
			base: "vs-dark",
			inherit: true,
			rules: [
				{ token: "comment", foreground: "616e88", fontStyle: "italic" },
				{ token: "keyword", foreground: "81a1c1" },
				{ token: "string", foreground: "a3be8c" },
				{ token: "number", foreground: "b48ead" },
				{ token: "operator", foreground: "88c0d0" },
				{ token: "function", foreground: "8fbcbb" },
				{ token: "variable", foreground: "d08770" },
				{ token: "type", foreground: "ebcb8b" },
			],
			colors: {
				"editor.background": "#2e3440",
				"editor.foreground": "#d8dee9",
				"editorLineNumber.foreground": "#4c566a",
				"editorCursor.foreground": "#88c0d0",
				"editor.selectionBackground": "#4c566a",
				"editor.wordHighlightBackground": "#434c5e",
				"editorIndentGuide.background": "#4c566a",
				"editorBracketMatch.background": "#4c566a",
				"editorBracketMatch.border": "#88c0d0",
				"editor.lineHighlightBackground": "#434c5e",
				"editor.lineHighlightBorder": "#434c5e",
			},
		},
	},
	vercel: {
		name: "Vercel",
		value: "vercel",
		ui: {
			background: "#000000",
			foreground: "#d1d5db",
			border: "#2d2d2d",
			accent: "#0070f3",
			selection: "#333333",
			header: "#000000",
			hover: "#1a1a1a",
			muted: "#828282",
			success: "#27c93f",
			warning: "#f7b500",
			error: "#f75252",
			info: "#3694ff",
		},
		monaco: {
			base: "vs-dark",
			inherit: true,
			colors: {
				"editor.background": "#000000",
				"editor.foreground": "#d1d5db",
				"editor.lineHighlightBackground": "#1a1a1a",
				"editor.lineHighlightBorder": "#1a1a1a",
				"editor.selectionBackground": "#333333",
				"editor.wordHighlightBackground": "#1f2937",
				"editorIndentGuide.background": "#2d2d2d",
				"editorBracketMatch.background": "#333333",
				"editorBracketMatch.border": "#4b5563",
				"editorLineNumber.foreground": "#4b5563",
				"editorCursor.foreground": "#0070f3",
			},
			rules: [
				{ token: "comment", foreground: "#6b7280", fontStyle: "italic" },
				{ token: "keyword", foreground: "#ff4c8d" },
				{ token: "string", foreground: "#10b981" },
				{ token: "number", foreground: "#fffff4" },
				{ token: "operator", foreground: "#ff4c8d" },
				{ token: "function", foreground: "#c372fc" },
				{ token: "variable", foreground: "#ff4c8d" },
				{ token: "type", foreground: "#47a8ff" },
			],
		},
	},
	tokyoNight: {
		name: "Tokyo Night",
		value: "tokyoNight",
		ui: {
			background: "#1a1b26",
			foreground: "#c0caf5",
			border: "#24283b",
			accent: "#7aa2f7",
			selection: "#33467c",
			header: "#1f2335",
			hover: "#2c3041",
			muted: "#565f89",
			success: "#9ece6a",
			warning: "#e0af68",
			error: "#f7768e",
			info: "#7dcfff",
		},
		monaco: {
			base: "vs-dark",
			inherit: true,
			rules: [
				{ token: "comment", foreground: "565f89", fontStyle: "italic" },
				{ token: "keyword", foreground: "bb9af7" },
				{ token: "string", foreground: "9ece6a" },
				{ token: "number", foreground: "ff9e64" },
				{ token: "operator", foreground: "7aa2f7" },
				{ token: "function", foreground: "7dcfff" },
				{ token: "variable", foreground: "f7768e" },
				{ token: "type", foreground: "e0af68" },
			],
			colors: {
				"editor.background": "#1a1b26",
				"editor.foreground": "#c0caf5",
				"editorLineNumber.foreground": "#565f89",
				"editorCursor.foreground": "#7aa2f7",
				"editor.selectionBackground": "#33467c",
				"editor.wordHighlightBackground": "#2c3041",
				"editorIndentGuide.background": "#24283b",
				"editorBracketMatch.background": "#3b4261",
				"editorBracketMatch.border": "#3b4261",
				"editor.lineHighlightBackground": "#292e42",
				"editor.lineHighlightBorder": "#292e42",
			},
		},
	},
	ayuMirage: {
		name: "Ayu Mirage",
		value: "ayuMirage",
		ui: {
			background: "#1f2430",
			foreground: "#cbccc6",
			border: "#3a3f4b",
			accent: "#39bae6",
			selection: "#273747",
			header: "#1f2430",
			hover: "#2c313c",
			muted: "#707a8a",
			success: "#a1cd5e",
			warning: "#ffcc66",
			error: "#f07178",
			info: "#5ccfe6",
		},
		monaco: {
			base: "vs-dark",
			inherit: true,
			rules: [
				{ token: "comment", foreground: "5c6773", fontStyle: "italic" },
				{ token: "keyword", foreground: "ffa759" },
				{ token: "string", foreground: "bae67e" },
				{ token: "number", foreground: "ffd580" },
				{ token: "operator", foreground: "5ccfe6" },
				{ token: "function", foreground: "73d0ff" },
				{ token: "variable", foreground: "ff3333" },
				{ token: "type", foreground: "ffc44c" },
			],
			colors: {
				"editor.background": "#1f2430",
				"editor.foreground": "#cbccc6",
				"editorLineNumber.foreground": "#5c6773",
				"editorCursor.foreground": "#39bae6",
				"editor.selectionBackground": "#273747",
				"editor.wordHighlightBackground": "#3a3f4b",
				"editorIndentGuide.background": "#3a3f4b",
				"editorBracketMatch.background": "#3a3f4b",
				"editorBracketMatch.border": "#3a3f4b",
				"editor.lineHighlightBackground": "#242936",
				"editor.lineHighlightBorder": "#242936",
			},
		},
	},
	candy: {
		name: "Candy",
		value: "candy",
		ui: {
			background: "#1e1e2e",
			foreground: "#d9e0ee",
			border: "#302d41",
			accent: "#f5c2e7",
			selection: "#45475a",
			header: "#24273a",
			hover: "#393552",
			muted: "#6e6a86",
			success: "#a6e3a1",
			warning: "#f9e2af",
			error: "#f38ba8",
			info: "#89b4fa",
		},
		monaco: {
			base: "vs-dark",
			inherit: true,
			rules: [
				{ token: "comment", foreground: "6e6a86", fontStyle: "italic" },
				{ token: "keyword", foreground: "cba6f7" },
				{ token: "string", foreground: "a6e3a1" },
				{ token: "number", foreground: "fab387" },
				{ token: "operator", foreground: "f5c2e7" },
				{ token: "function", foreground: "89b4fa" },
				{ token: "variable", foreground: "f38ba8" },
				{ token: "type", foreground: "f9e2af" },
			],
			colors: {
				"editor.background": "#1e1e2e",
				"editor.foreground": "#d9e0ee",
				"editorLineNumber.foreground": "#6e6a86",
				"editorCursor.foreground": "#f5c2e7",
				"editor.selectionBackground": "#45475a",
				"editor.wordHighlightBackground": "#393552",
				"editorIndentGuide.background": "#302d41",
				"editorBracketMatch.background": "#45475a",
				"editorBracketMatch.border": "#6e6a86",
				"editor.lineHighlightBackground": "#313244",
				"editor.lineHighlightBorder": "#313244",
			},
		},
	},
	suparbase: {
		name: "Suparbase",
		value: "suparbase",
		ui: {
			background: "#171717",
			foreground: "#9d9d9d",
			border: "#262c29",
			accent: "#3dcd8c",
			selection: "#9d9d9d22",
			header: "#171717",
			hover: "#454545",
			muted: "#D1D1D1",
			success: "#3dcd8c",
			warning: "#f9e2af",
			error: "#f38ba8",
			info: "#89b4fa",
		},

		monaco: {
			base: "vs-dark",
			inherit: true,
			rules: [
				{ token: "comment", foreground: "9d9d9d", fontStyle: "italic" },
				{ token: "keyword", foreground: "4af8aa" },
				{ token: "string", foreground: "ffffff80" },
				{ token: "number", foreground: "ffffff" },
				{ token: "operator", foreground: "ff4c8d" },
				{ token: "function", foreground: "c372fc" },
				{ token: "variable", foreground: "c372fc" },
				{ token: "type", foreground: "3dcd8c" },
				{ token: "constant", foreground: "a855f7" },
			],
			colors: {
				"editor.background": "#171717",
				"editor.foreground": "#9d9d9d",
				"editorLineNumber.foreground": "#4b5563",
				"editorCursor.foreground": "#00b4f7",
				"editor.selectionBackground": "#333333",
				"editor.wordHighlightBackground": "#1f2937",
				"editorIndentGuide.background": "#2d2d2d",
				"editorBracketMatch.background": "#333333",
				"editorBracketMatch.border": "#4b5563",
				"editor.lineHighlightBackground": "#1a1a1a",
				"editor.lineHighlightBorder": "#1a1a1a",
			},
		},
	},

	darkTheme: {
		name: "Custom Dark Theme",
		value: "custom-dark",
		ui: {
			background: "#0b1422", // Fondo oscuro para el editor
			foreground: "#D4D4D4", // Color principal del texto
			border: "#3C3C3C", // Bordes de paneles o secciones
			accent: "#569CD6", // Color de acento, similar al resaltado de variables o palabras clave
			selection: "#264F78", // Fondo de selección de texto
			header: "#0b1422", // Cabecera o títulos
			hover: "#264F78", // Color de fondo cuando se pasa el cursor sobre elementos
			muted: "#808080", // Texto o elementos menos destacados
			success: "#1E90FF", // Indicadores de éxito o confirmación
			warning: "#FF9877", // Indicadores de advertencia
			error: "#F44336", // Indicadores de error
			info: "#2196F3", // Indicadores de información adicional
		},
		monaco: {
			base: "vs-dark",
			inherit: true,
			rules: [
				{ token: "comment", foreground: "#98afbc" }, // Color para comentarios
				{ token: "keyword", foreground: "#42a9ee" }, // Palabras clave como `let`, `const`
				{ token: "string", foreground: "#fff3ff" }, // Color para cadenas de texto
				{ token: "number", foreground: "#43aef5" }, // Color para números
				{ token: "variable", foreground: "#3691d0" }, // Color para variables
				{ token: "type", foreground: "#42b3ff" }, // Tipos de datos
				{ token: "function", foreground: "#3ca0e5" }, // Color para funciones
				{ token: "constant", foreground: "#42b3ff" }, // Constantes
				{ token: "operator", foreground: "#8dc6e6" }, // Operadores como `??`, `=`
			],
			colors: {
				"editor.background": "#0b1422", // Fondo del editor
				"editor.foreground": "#D4D4D4", // Color principal del texto en el editor
				"editorCursor.foreground": "#FFFFFF", // Color del cursor
				"editorLineNumber.foreground": "#858585", // Color de los números de línea
				"editor.selectionBackground": "#264F78", // Fondo para el texto seleccionado
				"editor.inactiveSelectionBackground": "#3A3D41", // Fondo de selección inactiva
				"editor.lineHighlightBackground": "#2A2D2E", // Resaltado de la línea actual
				"editor.findMatchHighlightBackground": "#515C6A", // Resaltado de coincidencias de búsqueda
				"editorHoverWidget.background": "#252526", // Fondo de los widgets emergentes
				"editorHoverWidget.border": "#454545", // Borde de los widgets emergentes
				"editorSuggestWidget.background": "#252526", // Fondo del widget de sugerencias
				"editorSuggestWidget.border": "#454545", // Borde del widget de sugerencias
				"editorSuggestWidget.foreground": "#D4D4D4", // Color del texto en el widget de sugerencias
				"editorSuggestWidget.highlightForeground": "#569CD6", // Color de texto resaltado en sugerencias
			},
		},
	},
	synthwave84Theme: {
		name: "SynthWave '84",
		value: "synthwave84",
		ui: {
			background: "#2b213a",
			foreground: "#ffffff",
			border: "#6b4c7a",
			accent: "#ff6ac1",
			selection: "#6b4c7a",
			header: "#2b213a",
			hover: "#3b3052",
			muted: "#8e7c9a",
			success: "#3ad900",
			warning: "#ff9e64",
			error: "#f92aad",
			info: "#00f6ff",
		},
		monaco: {
			base: "vs-dark",
			inherit: true,
			rules: [
				{ token: "comment", foreground: "6272a4", fontStyle: "italic" },
				{ token: "keyword", foreground: "ff79c6" },
				{ token: "string", foreground: "f1fa8c" },
				{ token: "number", foreground: "bd93f9" },
				{ token: "operator", foreground: "ffb86c" },
				{ token: "function", foreground: "8be9fd" },
				{ token: "variable", foreground: "50fa7b" },
				{ token: "type", foreground: "50fa7b" },
			],
			colors: {
				"editor.background": "#2b213a",
				"editor.foreground": "#ffffff",
				"editorLineNumber.foreground": "#6272a4",
				"editorCursor.foreground": "#ff79c6",
				"editor.selectionBackground": "#44475a",
				"editor.wordHighlightBackground": "#44475a",
				"editorIndentGuide.background": "#44475a",
				"editorBracketMatch.background": "#44475a",
				"editorBracketMatch.border": "#50fa7b",
				"editor.lineHighlightBackground": "#44475a",
				"editor.lineHighlightBorder": "#44475a",
			},
		},
	},
};
